server:
  port: 8082
  
spring:
  application:
    name: course
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  jmx:
    enabled: false
  datasource:
    url: jdbc:mysql://localhost:4406/devdojo?allowPublicKeyRetrival=true&sslMode=DISABLED&useTimezone=true&serverTimezone=UTC
    username: root
    password: root

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/
    fetch-registry: true
    registry-with-eureka: true